name: dl_project
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.12.2
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - attrs==23.2.0
      - filelock==3.13.4
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - hydra-core==1.3.2
      - idna==3.7
      - jinja2==3.1.3
      - lightning==2.2.1
      - lightning-utilities==0.11.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - packaging==24.0
      - pillow==10.3.0
      - pytorch-lightning==2.2.1
      - pyyaml==6.0.1
      - sympy==1.12
      - torch==2.2.2
      - torchmetrics==1.3.2
      - torchvision==0.17.2
      - tqdm==4.66.2
      - typing-extensions==4.11.0
      - yarl==1.9.4