name: dl_project
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.2.0
  - arrow=1.2.3
  - backoff=2.2.1
  - beautifulsoup4=4.12.2
  - blas=1.0
  - blessed=1.20.0
  - boto3=1.29.1
  - botocore=1.32.1
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - croniter=1.3.7
  - dateutils=0.6.12
  - deepdiff=6.7.1
  - fastapi=0.103.0
  - filelock=3.13.1
  - fsspec=2023.10.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - h11=0.14.0
  - idna=3.4
  - inquirer=3.1.4
  - intel-openmp=2023.1.0
  - itsdangerous=2.0.1
  - jinja2=3.1.3
  - jmespath=1.0.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - lightning=2.0.9.post0
  - lightning-cloud=0.5.57
  - lightning-utilities=0.9.0
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.13
  - ordered-set=4.1.0
  - orjson=3.9.15
  - packaging=23.2
  - pip=23.3.1
  - psutil=5.9.0
  - pycparser=2.21
  - pydantic=1.10.12
  - pygments=2.15.1
  - pyjwt=2.4.0
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-editor=1.0.4
  - python-multipart=0.0.6
  - pytorch-lightning=2.0.3
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readchar=4.0.5
  - readline=8.2
  - requests=2.31.0
  - rich=13.3.5
  - s3transfer=0.7.0
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - starlette=0.27.0
  - starsessions=1.3.0
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchmetrics=1.1.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - urllib3=2.0.7
  - uvicorn=0.20.0
  - wcwidth=0.2.5
  - websocket-client=0.58.0
  - websockets=10.4
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - antlr4-python3-runtime==4.9.3
      - cachetools==5.3.3
      - google-auth==2.29.0
      - google-auth-oauthlib==1.2.0
      - grpcio==1.62.2
      - hydra-core==1.3.2
      - markdown==3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - pillow==10.3.0
      - protobuf==4.23.4
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - torch==2.2.2
      - torchvision==0.17.2
      - triton==2.2.0
      - werkzeug==3.0.2