core:
  name: test_vit
  output_dir: ./output/${core.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  mode: test
  #ckpt_path: null
  ckpt_path: /home/jack/Code/VITON/Deep-Learning-Project-S24/output/train_vit/2024-04-27/13-38-16/tb_logs/lightning_logs/version_0/checkpoints/epoch=31-step=46560.ckpt

hydra:
  run:
    dir: ${core.output_dir}

## Populated with default values from VITON-HD github
## Parameters explained in their respective classes
trainer:
  accelerator: auto
  max_epochs: 50
  default_root_dir: ${core.output_dir}
  #limit_train_batches: -1 # Included as debugging tool
  limit_val_batches: 6 # Included as debugging tool
  limit_test_batches: 1 # Included as debugging tool
  log_every_n_steps: 3

logger:
  save_dir: ${core.output_dir}/tb_logs

data:
  shuffle: True
  batch_size: 8
  workers: 1
  load_height: 512 #1024
  load_width: 384 #768
  semantic_nc: 13
  dataset_dir: data/zalando-hd-resized

model:
  _target_: dl_project.models.Vit_Lit
  embed_dim: 256
  hidden_dim: 512
  num_heads: 2
  num_layers: 3
  patch_size: 32
  in_channels: 22
  out_channels: 3
  num_patches: 192
  dropout: 0.2
  lr: 2e-4

