core:
  name: train_unet
  output_dir: ./output/${core.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

hydra:
  run:
    dir: ${core.output_dir}

## Populated with default values from VITON-HD github
## Parameters explained in their respective classes
trainer:
  accelerator: gpu
  max_epochs: 2
  default_root_dir: ${core.output_dir}
  limit_train_batches: 10 # Included as debugging tool
  limit_val_batches: 10 # Included as debugging tool
  log_every_n_steps: 5

data:
  shuffle: True
  batch_size: 1
  workers: 1
  load_height: 1024
  load_width: 768
  semantic_nc: 13
  dataset_dir: data/zalando-hd-resized

model:
  _target_: dl_project.models.UNetModel_Lit
  in_channels: 3
  out_channels: 3
  encoder_channels: [64, 128, 256, 512, 512, 512]
  decoder_channels: [512, 512, 256, 128, 64, 4]
  kernel_val: 4
  encoder_stride: 2
  decoder_stride: 0.5
  padding_val: 1
  lr: 2e-4

