core:
  name: train_unet
  output_dir: ./output/${core.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

hydra:
  run:
    dir: ${core.output_dir}

## Populated with default values from VITON-HD github
## Parameters explained in their respective classes
trainer:
  accelerator: auto
  max_epochs: 100
  default_root_dir: ${core.output_dir}
  limit_train_batches: 6 # Included as debugging tool
  limit_val_batches: 6 # Included as debugging tool
  log_every_n_steps: 3

logger:
  save_dir: ${core.output_dir}/tb_logs

data:
  shuffle: True
  batch_size: 8
  workers: 1
  load_height: 512
  load_width: 384
  semantic_nc: 13
  dataset_dir: data/zalando-hd-resized

model:
  _target_: dl_project.models.UNetModel_Lit
  in_channels: 22
  out_channels: 3
  encoder_channels: [64,128, 256, 512]
  decoder_channels: [512, 256, 128,64]
  kernel_val: 3
  encoder_stride: 1
  decoder_stride: 1
  padding_val: 1
  lr: 2e-3

